import { library } from '@fortawesome/fontawesome-svg-core';
import {
  faCalendarAlt,
  faClock,
  faEye,
  faEyeSlash,
  faPlusSquare,
  faWindowClose,
} from '@fortawesome/free-regular-svg-icons';
import {
  faUserSecret,
  faUser,
  faUserAlt,
  faEnvelope,
  faFolder,
  faQuestion,
  faSignOutAlt,
  faRandom,
  faArchive,
  faUserGraduate,
  faUserPlus,
  faArrowUp,
  faArrowDown,
  faCog,
  faLock,
  faPlusCircle,
  faHome,
  faUsers,
  faFileUpload,
  faFileDownload,
  faSave,
  faExchangeAlt,
  faEdit,
  faAt,
  faSignature,
  faPhone,
  faPencilAlt,
  faChevronRight,
  faChevronDown,
  faUserCheck,
  faPlay,
  faStop,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  faFolder,
  faQuestion,
  faSignOutAlt,
  faUser,
  faUserSecret,
  faUserAlt,
  faEnvelope,
  faRandom,
  faArchive,
  faUserGraduate,
  faUserPlus,
  faArrowUp,
  faArrowDown,
  faCog,
  faLock,
  faPlusCircle,
  faHome,
  faUsers,
  faPlusSquare,
  faFileUpload,
  faFileDownload,
  faSave,
  faWindowClose,
  faSignOutAlt,
  faExchangeAlt,
  faEdit,
  faClock,
  faCalendarAlt,
  faAt,
  faSignature,
  faPhone,
  faEye,
  faEyeSlash,
  faPencilAlt,
  faChevronRight,
  faChevronDown,
  faUserCheck,
  faPlay,
  faStop,
);

// $ npm i --save @fortawesome/free-brands-svg-icons //. fab
// $ npm i --save @fortawesome/free-regular-svg-icons //.far
//-A fas a alap
